# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:42:02+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class DfsSlatePlayer(BaseModel):
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerGameProjectionStatID: Optional[int] = None
    PlayerID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class News(BaseModel):
    Author: Optional[str] = None
    Categories: Optional[str] = None
    Content: Optional[str] = None
    NewsID: Optional[int] = None
    OriginalSource: Optional[str] = None
    OriginalSourceUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    PlayerID2: Optional[int] = None
    Source: Optional[str] = None
    Team: Optional[str] = None
    Team2: Optional[str] = None
    TeamID: Optional[int] = None
    TeamID2: Optional[int] = None
    TermsOfUse: Optional[str] = None
    TimeAgo: Optional[str] = None
    Title: Optional[str] = None
    Updated: Optional[str] = None
    Url: Optional[str] = None


class OpponentSeason(BaseModel):
    Assists: Optional[float] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[float] = None
    BlocksPercentage: Optional[float] = None
    DefensiveRebounds: Optional[float] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DoubleDoubles: Optional[float] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[float] = None
    FreeThrowsMade: Optional[float] = None
    FreeThrowsPercentage: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    IsClosed: Optional[bool] = None
    LineupConfirmed: Optional[bool] = None
    LineupStatus: Optional[str] = None
    Losses: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[float] = None
    OffensiveReboundsPercentage: Optional[float] = None
    OpponentPosition: Optional[str] = None
    PersonalFouls: Optional[float] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlusMinus: Optional[float] = None
    Points: Optional[float] = None
    Possessions: Optional[float] = None
    Rebounds: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[float] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[float] = None
    ThreePointersMade: Optional[float] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TripleDoubles: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[float] = None
    TwoPointersAttempted: Optional[float] = None
    TwoPointersMade: Optional[float] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    Wins: Optional[int] = None


class Player(BaseModel):
    BirthCity: Optional[str] = None
    BirthCountry: Optional[str] = None
    BirthDate: Optional[str] = None
    BirthState: Optional[str] = None
    College: Optional[str] = None
    DepthChartOrder: Optional[int] = None
    DepthChartPosition: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    Experience: Optional[int] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FirstName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Height: Optional[int] = None
    HighSchool: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Jersey: Optional[int] = None
    LastName: Optional[str] = None
    NbaDotComPlayerID: Optional[int] = None
    PhotoUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    Salary: Optional[int] = None
    SportRadarPlayerID: Optional[str] = None
    SportsDataID: Optional[str] = None
    SportsDirectPlayerID: Optional[int] = None
    StatsPlayerID: Optional[int] = None
    Status: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None
    XmlTeamPlayerID: Optional[int] = None
    YahooName: Optional[str] = None
    YahooPlayerID: Optional[int] = None


class PlayerGame(BaseModel):
    Assists: Optional[float] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[float] = None
    BlocksPercentage: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefensiveRebounds: Optional[float] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DoubleDoubles: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyDataSalary: Optional[int] = None
    FantasyDraftPosition: Optional[str] = None
    FantasyDraftSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[float] = None
    FreeThrowsMade: Optional[float] = None
    FreeThrowsPercentage: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    HomeOrAway: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    IsClosed: Optional[bool] = None
    IsGameOver: Optional[bool] = None
    LineupConfirmed: Optional[bool] = None
    LineupStatus: Optional[str] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[float] = None
    OffensiveReboundsPercentage: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpponentPositionRank: Optional[int] = None
    OpponentRank: Optional[int] = None
    PersonalFouls: Optional[float] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlayerID: Optional[int] = None
    PlusMinus: Optional[float] = None
    Points: Optional[float] = None
    Position: Optional[str] = None
    Rebounds: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[float] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[float] = None
    ThreePointersMade: Optional[float] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TripleDoubles: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[float] = None
    TwoPointersAttempted: Optional[float] = None
    TwoPointersMade: Optional[float] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None


class PlayerInfo(BaseModel):
    Name: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class PlayerSeason(BaseModel):
    Assists: Optional[float] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[float] = None
    BlocksPercentage: Optional[float] = None
    DefensiveRebounds: Optional[float] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DoubleDoubles: Optional[float] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[float] = None
    FreeThrowsMade: Optional[float] = None
    FreeThrowsPercentage: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    IsClosed: Optional[bool] = None
    LineupConfirmed: Optional[bool] = None
    LineupStatus: Optional[str] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[float] = None
    OffensiveReboundsPercentage: Optional[float] = None
    PersonalFouls: Optional[float] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlayerID: Optional[int] = None
    PlusMinus: Optional[float] = None
    Points: Optional[float] = None
    Position: Optional[str] = None
    Rebounds: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[float] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[float] = None
    ThreePointersMade: Optional[float] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TripleDoubles: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[float] = None
    TwoPointersAttempted: Optional[float] = None
    TwoPointersMade: Optional[float] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None


class Quarter(BaseModel):
    AwayScore: Optional[int] = None
    GameID: Optional[int] = None
    HomeScore: Optional[int] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    QuarterID: Optional[int] = None


class Season(BaseModel):
    ApiSeason: Optional[str] = None
    Description: Optional[str] = None
    EndYear: Optional[int] = None
    PostSeasonStartDate: Optional[str] = None
    RegularSeasonStartDate: Optional[str] = None
    Season: Optional[int] = None
    SeasonType: Optional[str] = None
    StartYear: Optional[int] = None


class Series(BaseModel):
    AwayTeamWins: Optional[int] = None
    GameNumber: Optional[int] = None
    HomeTeamWins: Optional[int] = None
    MaxLength: Optional[int] = None


class Stadium(BaseModel):
    Active: Optional[bool] = None
    Address: Optional[str] = None
    Capacity: Optional[int] = None
    City: Optional[str] = None
    Country: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    Name: Optional[str] = None
    StadiumID: Optional[int] = None
    State: Optional[str] = None
    Zip: Optional[str] = None


class Standing(BaseModel):
    AwayLosses: Optional[int] = None
    AwayWins: Optional[int] = None
    City: Optional[str] = None
    Conference: Optional[str] = None
    ConferenceLosses: Optional[int] = None
    ConferenceRank: Optional[int] = None
    ConferenceWins: Optional[int] = None
    Division: Optional[str] = None
    DivisionLosses: Optional[int] = None
    DivisionRank: Optional[int] = None
    DivisionWins: Optional[int] = None
    GamesBack: Optional[float] = None
    GlobalTeamID: Optional[int] = None
    HomeLosses: Optional[int] = None
    HomeWins: Optional[int] = None
    Key: Optional[str] = None
    LastTenLosses: Optional[int] = None
    LastTenWins: Optional[int] = None
    Losses: Optional[int] = None
    Name: Optional[str] = None
    Percentage: Optional[float] = None
    PointsPerGameAgainst: Optional[float] = None
    PointsPerGameFor: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Streak: Optional[int] = None
    StreakDescription: Optional[str] = None
    TeamID: Optional[int] = None
    Wins: Optional[int] = None


class Team(BaseModel):
    Active: Optional[bool] = None
    City: Optional[str] = None
    Conference: Optional[str] = None
    Division: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Key: Optional[str] = None
    LeagueID: Optional[int] = None
    Name: Optional[str] = None
    NbaDotComTeamID: Optional[int] = None
    PrimaryColor: Optional[str] = None
    QuaternaryColor: Optional[str] = None
    SecondaryColor: Optional[str] = None
    StadiumID: Optional[int] = None
    TeamID: Optional[int] = None
    TertiaryColor: Optional[str] = None
    WikipediaLogoUrl: Optional[str] = None
    WikipediaWordMarkUrl: Optional[str] = None


class TeamGame(BaseModel):
    Assists: Optional[float] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[float] = None
    BlocksPercentage: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefensiveRebounds: Optional[float] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DoubleDoubles: Optional[float] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[float] = None
    FreeThrowsMade: Optional[float] = None
    FreeThrowsPercentage: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    HomeOrAway: Optional[str] = None
    IsClosed: Optional[bool] = None
    IsGameOver: Optional[bool] = None
    LineupConfirmed: Optional[bool] = None
    LineupStatus: Optional[str] = None
    Losses: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[float] = None
    OffensiveReboundsPercentage: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    PersonalFouls: Optional[float] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlusMinus: Optional[float] = None
    Points: Optional[float] = None
    Possessions: Optional[float] = None
    Rebounds: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[float] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[float] = None
    ThreePointersMade: Optional[float] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TripleDoubles: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[float] = None
    TwoPointersAttempted: Optional[float] = None
    TwoPointersMade: Optional[float] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    Wins: Optional[int] = None


class TeamSeason(BaseModel):
    Assists: Optional[float] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[float] = None
    BlocksPercentage: Optional[float] = None
    DefensiveRebounds: Optional[float] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DoubleDoubles: Optional[float] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[float] = None
    FreeThrowsMade: Optional[float] = None
    FreeThrowsPercentage: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    IsClosed: Optional[bool] = None
    LineupConfirmed: Optional[bool] = None
    LineupStatus: Optional[str] = None
    Losses: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[float] = None
    OffensiveReboundsPercentage: Optional[float] = None
    OpponentPosition: Optional[str] = None
    OpponentStat: Optional[OpponentSeason] = None
    PersonalFouls: Optional[float] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlusMinus: Optional[float] = None
    Points: Optional[float] = None
    Possessions: Optional[float] = None
    Rebounds: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[float] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[float] = None
    ThreePointersMade: Optional[float] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TripleDoubles: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[float] = None
    TwoPointersAttempted: Optional[float] = None
    TwoPointersMade: Optional[float] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    Wins: Optional[int] = None


class FieldFormatAllStarsSeasonGetResponse(RootModel[List[PlayerInfo]]):
    root: List[PlayerInfo]


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatAllTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class FieldFormatFreeAgentsGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatNewsGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByDateDateGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByPlayerIDPlayeridGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatPlayerGameStatsByDateDateGetResponse(RootModel[List[PlayerGame]]):
    root: List[PlayerGame]


class FieldFormatPlayerGameStatsBySeasonSeasonPlayeridNumberofgamesGetResponse(
    RootModel[List[PlayerGame]]
):
    root: List[PlayerGame]


class FieldFormatPlayerSeasonStatsSeasonGetResponse(RootModel[List[PlayerSeason]]):
    root: List[PlayerSeason]


class FieldFormatPlayerSeasonStatsByTeamSeasonTeamGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class FieldFormatPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatPlayersTeamGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatStadiumsGetResponse(RootModel[List[Stadium]]):
    root: List[Stadium]


class Format23(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatStandingsSeasonGetResponse(RootModel[List[Standing]]):
    root: List[Standing]


class Format24(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatTeamGameStatsByDateDateGetResponse(RootModel[List[TeamGame]]):
    root: List[TeamGame]


class FieldFormatTeamGameStatsBySeasonSeasonTeamidNumberofgamesGetResponse(
    RootModel[List[TeamGame]]
):
    root: List[TeamGame]


class FieldFormatTeamSeasonStatsSeasonGetResponse(RootModel[List[TeamSeason]]):
    root: List[TeamSeason]


class FieldFormatTeamStatsAllowedByPositionSeasonGetResponse(
    RootModel[List[TeamSeason]]
):
    root: List[TeamSeason]


class FieldFormatTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class Game(BaseModel):
    AlternateID: Optional[int] = None
    Attendance: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    Channel: Optional[str] = None
    CrewChiefID: Optional[int] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    GameEndDateTime: Optional[str] = None
    GameID: Optional[int] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeRotationNumber: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    IsClosed: Optional[bool] = None
    LastPlay: Optional[str] = None
    NeutralVenue: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    PointSpread: Optional[float] = None
    PointSpreadAwayTeamMoneyLine: Optional[int] = None
    PointSpreadHomeTeamMoneyLine: Optional[int] = None
    Quarter: Optional[str] = None
    Quarters: Optional[List[Quarter]] = None
    RefereeID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SeriesInfo: Optional[Series] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None
    UmpireID: Optional[int] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None


class FieldFormatGamesSeasonGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatGamesByDateDateGetResponse(RootModel[List[Game]]):
    root: List[Game]


class BoxScore(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    PlayerGames: Optional[List[PlayerGame]] = None
    Quarters: Optional[List[Quarter]] = None
    TeamGames: Optional[List[TeamGame]] = None


class DfsSlateGame(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    GameID: Optional[int] = None
    OperatorGameID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None


class FieldFormatBoxScoresDateGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class FieldFormatBoxScoresDeltaDateMinutesGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class DfsSlate(BaseModel):
    DfsSlateGames: Optional[List[DfsSlateGame]] = None
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfGames: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SalaryCap: Optional[int] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None


class FieldFormatDfsSlatesByDateDateGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]
